language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8

install:
  - "npm install -g npm"
  - "npm install"
  - "pip install Django==$DJANGO_VERSION"
  - "pip install -r requirements.txt"

script: python runtests.py
